name: "Apk size tracker"
description: "Track the size of apk"
inputs:
  flavor: # id of input
    description: "flavor of the apk to build"
    required: true
    default: "staging"
  GITHUB_TOKEN:
    description: "GitHub token"
    required: true
  threshold:
    description: "Permissible size threshold above which merging will be blocked"
    required: false
  is-react-native:
    description: "is it a react native project"
    required: false
    default: false
  rn_change:
    description: "RN files changed"
    required: true
    default: false
  native_change:
    description: "Native files changed"
    required: true
    default: false
  yarn_lock_change:
    description: "yarn.lock file changes"
    required: true
    default: false
  bundle-command:
    description: "Bundle command"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
