name: "Apk size tracker"
description: "Track the size of apk"
inputs:
  flavor: # id of input
    description: "flavor of the apk to build"
    required: true
    default: "staging"
  github_token:
    description: "GitHub token"
    required: true
  threshold:
    description: "Permissible size threshold above which merging will be blocked"
    required: false
    default: "100"
  is_react_native:
    description: "is it a react native project"
    required: false
    default: false
  rn_change:
    description: "RN files changed"
    required: true
    default: false
  native_change:
    description: "Native files changed"
    required: true
    default: false
  yarn_lock_change:
    description: "yarn.lock file changes"
    required: true
    default: false
  bundle_command:
    description: "Bundle command"
    required: true
  working_directory:
      description: "Working Directory"
      required: false
  stream_output_max_buffer:
    description: "stream_output_max_buffer command"
    required: false
    default: "1"
runs:
  using: "node16"
  main: "dist/index.js"
